-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Mar 24, 2026 at 11:40 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `i-rate_movies`
--

-- --------------------------------------------------------

--
-- Table structure for table `movies`
--

DROP TABLE IF EXISTS `movies`;
CREATE TABLE IF NOT EXISTS `movies` (
  `movie_id` int(11) NOT NULL AUTO_INCREMENT,
  `imdb_id` varchar(20) NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `year` int(4) DEFAULT NULL,
  `genre` enum('Action','Adventure','Animation','Biography','Comedy','Crime','Documentary','Drama','Family','Fantasy','History','Horror','Music','Musical','Mystery','Romance','Sci-Fi','Sport','Thriller','War','Western','Other') DEFAULT NULL,
  `description` text DEFAULT NULL,
  `actors` varchar(255) DEFAULT NULL,
  `image_url` varchar(255) DEFAULT NULL,
  `avg_rating` decimal(3,2) DEFAULT 0.00,
  PRIMARY KEY (`movie_id`),
  UNIQUE KEY `imdb_id` (`imdb_id`)
) ENGINE=InnoDB AUTO_INCREMENT=230 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `movies`
--

INSERT INTO `movies` (`movie_id`, `imdb_id`, `title`, `year`, `genre`, `description`, `actors`, `image_url`, `avg_rating`) VALUES
(3, 'tt3896198', 'Guardians of the Galaxy Vol. 2', 2017, 'Action', 'The Guardians struggle to keep together as a team while dealing with their personal family issues, notably Star-Lord\'s encounter with his father, the ambitious celestial being Ego.', 'Chris Pratt, Zoe Saldaña, Dave Bautista', 'https://m.media-amazon.com/images/M/MV5BNWE5MGI3MDctMmU5Ni00YzI2LWEzMTQtZGIyZDA5MzQzNDBhXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(19, 'tt0133093', 'The Matrix', 1999, 'Action', 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.', 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss', 'https://m.media-amazon.com/images/M/MV5BN2NmN2VhMTQtMDNiOS00NDlhLTliMjgtODE2ZTY0ODQyNDRhXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(20, 'tt0111161', 'The Shawshank Redemption', 1994, 'Drama', 'A banker convicted of uxoricide forms a friendship over a quarter century with a hardened convict, while maintaining his innocence and trying to remain hopeful through simple compassion.', 'Tim Robbins, Morgan Freeman, Bob Gunton', 'https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(21, 'tt0068646', 'The Godfather', 1972, 'Crime', 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.', 'Marlon Brando, Al Pacino, James Caan', 'https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(22, 'tt0071562', 'The Godfather Part II', 1974, 'Crime', 'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.', 'Al Pacino, Robert De Niro, Robert Duvall', 'https://m.media-amazon.com/images/M/MV5BMDIxMzBlZDktZjMxNy00ZGI4LTgxNDEtYWRlNzRjMjJmOGQ1XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(23, 'tt0468569', 'The Dark Knight', 2008, 'Action', 'When a menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman, James Gordon and Harvey Dent must work together to put an end to the madness.', 'Christian Bale, Heath Ledger, Aaron Eckhart', 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg', 0.00),
(24, 'tt0050083', '12 Angry Men', 1957, 'Crime', 'The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.', 'Henry Fonda, Lee J. Cobb, Martin Balsam', 'https://m.media-amazon.com/images/M/MV5BYjE4NzdmOTYtYjc5Yi00YzBiLWEzNDEtNTgxZGQ2MWVkN2NiXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(25, 'tt0108052', 'Schindler\'s List', 1993, 'Biography', 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.', 'Liam Neeson, Ralph Fiennes, Ben Kingsley', 'https://m.media-amazon.com/images/M/MV5BNjM1ZDQxYWUtMzQyZS00MTE1LWJmZGYtNGUyNTdlYjM3ZmVmXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(26, 'tt0167260', 'The Lord of the Rings: The Return of the King', 2003, 'Adventure', 'Gandalf and Aragorn lead the World of Men against Sauron\'s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.', 'Elijah Wood, Viggo Mortensen, Ian McKellen', 'https://m.media-amazon.com/images/M/MV5BMTZkMjBjNWMtZGI5OC00MGU0LTk4ZTItODg2NWM3NTVmNWQ4XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(27, 'tt0110912', 'Pulp Fiction', 1994, 'Crime', 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 'John Travolta, Uma Thurman, Samuel L. Jackson', 'https://m.media-amazon.com/images/M/MV5BYTViYTE3ZGQtNDBlMC00ZTAyLTkyODMtZGRiZDg0MjA2YThkXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(28, 'tt0060196', 'The Good, the Bad and the Ugly', 1966, 'Adventure', 'A bounty-hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.', 'Clint Eastwood, Eli Wallach, Lee Van Cleef', 'https://m.media-amazon.com/images/M/MV5BMWM5ZjQxM2YtNDlmYi00ZDNhLWI4MWUtN2VkYjBlMTY1ZTkwXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(29, 'tt0137523', 'Fight Club', 1999, 'Crime', 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.', 'Brad Pitt, Edward Norton, Meat Loaf', 'https://m.media-amazon.com/images/M/MV5BOTgyOGQ1NDItNGU3Ny00MjU3LTg2YWEtNmEyYjBiMjI1Y2M5XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(30, 'tt0120737', 'The Lord of the Rings: The Fellowship of the Ring', 2001, 'Adventure', 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.', 'Elijah Wood, Ian McKellen, Orlando Bloom', 'https://m.media-amazon.com/images/M/MV5BNzIxMDQ2YTctNDY4MC00ZTRhLTk4ODQtMTVlOWY4NTdiYmMwXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(31, 'tt0109830', 'Forrest Gump', 1994, 'Drama', 'The history of the United States from the 1950s to the \'70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.', 'Tom Hanks, Robin Wright, Gary Sinise', 'https://m.media-amazon.com/images/M/MV5BNDYwNzVjMTItZmU5YS00YjQ5LTljYjgtMjY2NDVmYWMyNWFmXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(32, 'tt0080684', 'Star Wars: Episode V - The Empire Strikes Back', 1980, 'Action', 'After the Empire overpowers the Rebel Alliance, Luke Skywalker begins training with Jedi Master Yoda, while Darth Vader and bounty hunter Boba Fett pursue his friends across the galaxy.', 'Mark Hamill, Harrison Ford, Carrie Fisher', 'https://m.media-amazon.com/images/M/MV5BMTkxNGFlNDktZmJkNC00MDdhLTg0MTEtZjZiYWI3MGE5NWIwXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(33, 'tt1375666', 'Inception', 2010, 'Action', 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO, but his tragic past may doom the project and his team to disaster.', 'Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page', 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg', 0.00),
(34, 'tt0167261', 'The Lord of the Rings: The Two Towers', 2002, 'Adventure', 'While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron\'s new ally, Saruman, and his hordes of Isengard.', 'Elijah Wood, Ian McKellen, Viggo Mortensen', 'https://m.media-amazon.com/images/M/MV5BMGQxMDdiOWUtYjc1Ni00YzM1LWE2NjMtZTg3Y2JkMjEzMTJjXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(35, 'tt0073486', 'One Flew Over the Cuckoo\'s Nest', 1975, 'Drama', 'A rebellious convict is sent to a psychiatric hospital for evaluation in 1963 Oregon, and encourages his docile companions to take more control of their lives and defy the tyrannical head nurse.', 'Jack Nicholson, Louise Fletcher, Michael Berryman', 'https://m.media-amazon.com/images/M/MV5BYjBkMjgzMzYtNzRiMS00NDc3LWE4YTUtZjYxYjZhNjNhYzhhXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(36, 'tt0099685', 'Goodfellas', 1990, 'Biography', 'The story of Henry Hill and his life in the mafia, covering his relationship with his wife Karen and his mob partners Jimmy Conway and Tommy DeVito.', 'Robert De Niro, Ray Liotta, Joe Pesci', 'https://m.media-amazon.com/images/M/MV5BN2E5NzI2ZGMtY2VjNi00YTRjLWI1MDUtZGY5OWU1MWJjZjRjXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(38, 'tt0047478', 'Seven Samurai', 1954, 'Action', 'Farmers from a village exploited by bandits hire a veteran samurai for protection, and he gathers six other samurai to join him.', 'Toshirô Mifune, Takashi Shimura, Keiko Tsushima', 'https://m.media-amazon.com/images/M/MV5BZjliMWExOTMtZDQ3ZS00NWU3LWIyN2EtMjllNzk3ZTNlYzg4XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(39, 'tt0114369', 'Se7en', 1995, 'Crime', 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.', 'Morgan Freeman, Brad Pitt, Kevin Spacey', 'https://m.media-amazon.com/images/M/MV5BY2IzNzMxZjctZjUxZi00YzAxLTk3ZjMtODFjODdhMDU5NDM1XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(40, 'tt0317248', 'City of God', 2002, 'Crime', 'In the slums of Rio, two kids\' paths diverge as one struggles to become a photographer and the other a kingpin.', 'Alexandre Rodrigues, Leandro Firmino, Matheus Nachtergaele', 'https://m.media-amazon.com/images/M/MV5BYjY4NGI5OTUtY2ZlZS00Zjk4LTk5N2MtN2JmYWVjNGNmMGRlXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(41, 'tt0102926', 'The Silence of the Lambs', 1991, 'Crime', 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.', 'Jodie Foster, Anthony Hopkins, Scott Glenn', 'https://m.media-amazon.com/images/M/MV5BNDdhOGJhYzctYzYwZC00YmI2LWI0MjctYjg4ODdlMDExYjBlXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(42, 'tt0038650', 'It\'s a Wonderful Life', 1946, 'Drama', 'An angel is sent from Heaven to help a desperately frustrated businessman see the value of his own life.', 'James Stewart, Donna Reed, Lionel Barrymore', 'https://m.media-amazon.com/images/M/MV5BMDM4OWFhYjEtNTE5Yy00NjcyLTg5N2UtZDQwNDZlYjlmNDU5XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(43, 'tt0118799', 'Life Is Beautiful', 1997, 'Comedy', 'When an open-minded Jewish waiter and his son become victims of the Holocaust, he uses a perfect mixture of will, humor and imagination to protect his son from the dangers around their camp.', 'Roberto Benigni, Nicoletta Braschi, Giorgio Cantarini', 'https://m.media-amazon.com/images/M/MV5BZTBhOGYzZjQtYzE0Mi00MGIwLWE0MWYtNzMxNTM2OTFkM2NjXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(44, 'tt0120815', 'Saving Private Ryan', 1998, 'Drama', 'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose comrades have been killed in action.', 'Tom Hanks, Matt Damon, Tom Sizemore', 'https://m.media-amazon.com/images/M/MV5BZGZhZGQ1ZWUtZTZjYS00MDJhLWFkYjctN2ZlYjE5NWYwZDM2XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(45, 'tt0088763', 'Back to the Future', 1985, 'Adventure', 'Marty McFly, a 17-year-old high school student, is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his close friend, the maverick scientist Doc Brown.', 'Michael J. Fox, Christopher Lloyd, Lea Thompson', 'https://m.media-amazon.com/images/M/MV5BZmM3ZjE0NzctNjBiOC00MDZmLTgzMTUtNGVlOWFlOTNiZDJiXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(46, 'tt0103064', 'Terminator 2: Judgment Day', 1991, 'Action', 'A cyborg from the future, identical to the one who failed to kill Sarah Connor, must now protect her ten-year-old son John from an even more advanced and powerful cyborg.', 'Arnold Schwarzenegger, Linda Hamilton, Edward Furlong', 'https://m.media-amazon.com/images/M/MV5BNGMyMGNkMDUtMjc2Ni00NWFlLTgyODEtZTY2MzBiZTg0OWZiXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(47, 'tt0076759', 'Star Wars: Episode IV - A New Hope', 1977, 'Action', 'Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire\'s world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth ...', 'Mark Hamill, Harrison Ford, Carrie Fisher', 'https://m.media-amazon.com/images/M/MV5BOGUwMDk0Y2MtNjBlNi00NmRiLTk2MWYtMGMyMDlhYmI4ZDBjXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(48, 'tt0245429', 'Spirited Away', 2001, 'Animation', 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches and spirits, and where humans are changed into beasts.', 'Miyu Irino, Rumi Hiiragi, Mari Natsuki', 'https://m.media-amazon.com/images/M/MV5BNTEyNmEwOWUtYzkyOC00ZTQ4LTllZmUtMjk0Y2YwOGUzYjRiXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(49, 'tt6751668', 'Parasite', 2019, 'Drama', 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.', 'Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong', 'https://m.media-amazon.com/images/M/MV5BYjk1Y2U4MjQtY2ZiNS00OWQyLWI3MmYtZWUwNmRjYWRiNWNhXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(50, 'tt0110413', 'Léon: The Professional', 1994, 'Action', 'When her family is murdered by a group of corrupt officers led by the tyrannical Norman Stansfield, a young 12-year-old girl enlists the help of an Italian-American hitman to seek revenge.', 'Jean Reno, Gary Oldman, Natalie Portman', 'https://m.media-amazon.com/images/M/MV5BNGRkYTNhOWQtYmI0Ni00MjZhLWJmMzAtMTA2Mjg4NGNiNDU0XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(51, 'tt0120689', 'The Green Mile', 1999, 'Crime', 'A death row guard learns that a gentle giant in his charge possesses a mysterious gift.', 'Tom Hanks, Michael Clarke Duncan, David Morse', 'https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_SX300.jpg', 0.00),
(52, 'tt0816692', 'Interstellar', 2014, 'Adventure', 'When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.', 'Matthew McConaughey, Anne Hathaway, Jessica Chastain', 'https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(53, 'tt0114814', 'The Usual Suspects', 1995, 'Crime', 'The sole survivor of a pier shoot-out tells the story of how a notorious criminal influenced the events that began with five criminals meeting in a seemingly random police lineup.', 'Kevin Spacey, Gabriel Byrne, Chazz Palminteri', 'https://m.media-amazon.com/images/M/MV5BOTE5MDUxZDUtZWZmZC00NDVmLWFhOGQtNWI2YTc4NzY3MGQ0XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(54, 'tt0120586', 'American History X', 1998, 'Crime', 'A white supremacist is released from prison a changed man and hopes to prevent his younger brother from following in his footsteps.', 'Edward Norton, Edward Furlong, Beverly D\'Angelo', 'https://m.media-amazon.com/images/M/MV5BMzhiOTQ0NDItOTg0Zi00OGVmLWE0OGEtMTI4NDM0NWMxZWU4XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(55, 'tt0054215', 'Psycho', 1960, 'Drama', 'A secretary on the run for embezzlement takes refuge at a secluded California motel owned by a repressed man and his overbearing mother.', 'Anthony Perkins, Janet Leigh, Vera Miles', 'https://m.media-amazon.com/images/M/MV5BYjZhMzFiZjItODA3ZC00MmRhLWIzMGYtMmVjOWUwYTA3MTRjXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(56, 'tt0253474', 'The Pianist', 2002, 'Biography', 'During WWII, acclaimed Polish musician Wladyslaw faces various struggles as he loses contact with his family. As the situation worsens, he hides in the ruins of Warsaw in order to survive.', 'Adrien Brody, Thomas Kretschmann, Frank Finlay', 'https://m.media-amazon.com/images/M/MV5BMjEwNmEwYjgtNTk3ZC00NjljLTg5ZDctZTY3ZGQwZjRkZmQxXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(57, 'tt0105236', 'Reservoir Dogs', 1992, 'Crime', 'When a simple jewelry heist goes horribly wrong, the surviving criminals begin to suspect that one of them is a police informant.', 'Harvey Keitel, Tim Roth, Michael Madsen', 'https://m.media-amazon.com/images/M/MV5BMmMzYjg4NDctYWY0Mi00OGViLWIzMTMtYWNlZGY5ZDJmYjk3XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(58, 'tt0172495', 'Gladiator', 2000, 'Action', 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.', 'Russell Crowe, Joaquin Phoenix, Connie Nielsen', 'https://m.media-amazon.com/images/M/MV5BYWQ4YmNjYjEtOWE1Zi00Y2U4LWI4NTAtMTU0MjkxNWQ1ZmJiXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(59, 'tt0027977', 'Modern Times', 1936, 'Comedy', 'The Tramp struggles to live in modern industrial society with the help of a young homeless woman.', 'Charles Chaplin, Paulette Goddard, Henry Bergman', 'https://m.media-amazon.com/images/M/MV5BODVkZGFhNGQtYjdiYi00Njc4LWFmYTItNTlmNzJjMTg1ZDc5XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(60, 'tt0082971', 'Raiders of the Lost Ark', 1981, 'Action', 'In 1936, archaeologist Indiana Jones is tasked by Army Intelligence to help locate a legendary ancient power, the Ark of Covenant, before the Nazis get it first.', 'Harrison Ford, Karen Allen, Paul Freeman', 'https://m.media-amazon.com/images/M/MV5BOGNhMjg2ZjgtYzk4Ni00MTViLTg1MmUtYzM2MDZiYjZlMmU3XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(61, 'tt0407887', 'The Departed', 2006, 'Crime', 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.', 'Leonardo DiCaprio, Matt Damon, Jack Nicholson', 'https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_SX300.jpg', 0.00),
(62, 'tt0482571', 'The Prestige', 2006, 'Drama', 'Two friends and fellow magicians become bitter enemies after a sudden tragedy. As they devote themselves to this rivalry, they make sacrifices that bring them fame but, with terrible consequences.', 'Christian Bale, Hugh Jackman, Scarlett Johansson', 'https://m.media-amazon.com/images/M/MV5BMTM3MzQ5MjQ5OF5BMl5BanBnXkFtZTcwMTQ3NzMzMw@@._V1_SX300.jpg', 0.00),
(63, 'tt2582802', 'Whiplash', 2014, 'Drama', 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student\'s potential.', 'Miles Teller, J.K. Simmons, Melissa Benoist', 'https://m.media-amazon.com/images/M/MV5BMDFjOWFkYzktYzhhMC00NmYyLTkwY2EtYjViMDhmNzg0OGFkXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(64, 'tt0034583', 'Casablanca', 1942, 'Drama', 'A cynical expatriate American cafe owner struggles to decide whether or not to help his former lover and her fugitive husband escape the Nazis in French Morocco.', 'Humphrey Bogart, Ingrid Bergman, Paul Henreid', 'https://m.media-amazon.com/images/M/MV5BNWEzN2U1YTYtYTQyMS00NTVkLWE2NGQtZWFlMmM0MDNjMmRiXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(65, 'tt0090605', 'Aliens', 1986, 'Action', 'Decades after surviving the Nostromo incident, Ellen Ripley is sent out to re-establish contact with a terraforming colony but finds herself battling the Alien Queen and her offspring.', 'Sigourney Weaver, Michael Biehn, Carrie Henn', 'https://m.media-amazon.com/images/M/MV5BZjIyNGJhYzYtN2I1My00OTVhLWEyMzItZTVjNDMzOTVkYWViXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(66, 'tt0047396', 'Rear Window', 1954, 'Drama', 'A bored photographer recovering from a broken leg passes the time by watching his neighbors and begins to suspect one of them of murder.', 'James Stewart, Grace Kelly, Wendell Corey', 'https://m.media-amazon.com/images/M/MV5BODZhOWI1ODgtMzdiOS00YjNkLTgwOGUtYmIyZDg5ZmQwMzQ1XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(67, 'tt0078788', 'Apocalypse Now', 1979, 'Drama', 'A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces Colonel who sees himself as a god.', 'Martin Sheen, Marlon Brando, Robert Duvall', 'https://m.media-amazon.com/images/M/MV5BZDhiMTljYjYtODc1Yy00MmEwLTg2OTYtYmE1YTRmNDE4MmEwXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(68, 'tt0081505', 'The Shining', 1980, 'Drama', 'A family heads to an isolated hotel for the winter, where a sinister presence influences the father into violence. At the same time, his psychic son sees horrifying forebodings from both the past and the future.', 'Jack Nicholson, Shelley Duvall, Danny Lloyd', 'https://m.media-amazon.com/images/M/MV5BNmM5ZThhY2ItOGRjOS00NzZiLWEwYTItNDgyMjFkOTgxMmRiXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(69, 'tt0110357', 'The Lion King', 1994, 'Animation', 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.', 'Matthew Broderick, Jeremy Irons, James Earl Jones', 'https://m.media-amazon.com/images/M/MV5BZGRiZDZhZjItM2M3ZC00Y2IyLTk3Y2MtMWY5YjliNDFkZTJlXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(70, 'tt1853728', 'Django Unchained', 2012, 'Drama', 'With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation owner in Mississippi.', 'Jamie Foxx, Christoph Waltz, Leonardo DiCaprio', 'https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_SX300.jpg', 0.00),
(71, 'tt0910970', 'WALL·E', 2008, 'Animation', 'A robot who is responsible for cleaning a waste-covered Earth meets another robot and falls in love with her. Together, they set out on a journey that will alter the fate of mankind.', 'Ben Burtt, Elissa Knight, Jeff Garlin', 'https://m.media-amazon.com/images/M/MV5BMjExMTg5OTU0NF5BMl5BanBnXkFtZTcwMjMxMzMzMw@@._V1_SX300.jpg', 0.00),
(72, 'tt0086879', 'Amadeus', 1984, 'Biography', 'The life and work of Wolfgang Amadeus Mozart seen through the eyes of his contemporary and rival, Antonio Salieri.', 'F. Murray Abraham, Tom Hulce, Elizabeth Berridge', 'https://m.media-amazon.com/images/M/MV5BMzc2MjM0NTMtOGY4NC00NzY1LWE2ODUtZjMzY2RhNGNkZDAyXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(73, 'tt4154796', 'Avengers: Endgame', 2019, 'Action', 'After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos\' actions and restore balance to the universe.', 'Robert Downey Jr., Chris Evans, Mark Ruffalo', 'https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX300.jpg', 0.00),
(74, 'tt4633694', 'Spider-Man: Into the Spider-Verse', 2018, 'Animation', 'Teen Miles Morales becomes the Spider-Man of his universe and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.', 'Shameik Moore, Jake Johnson, Hailee Steinfeld', 'https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgzOF5BMl5BanBnXkFtZTgwNTkwNTQ3NjM@._V1_SX300.jpg', 0.00),
(75, 'tt4154756', 'Avengers: Infinity War', 2018, 'Action', 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.', 'Robert Downey Jr., Chris Hemsworth, Mark Ruffalo', 'https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_SX300.jpg', 0.00),
(77, 'tt1345836', 'The Dark Knight Rises', 2012, 'Action', 'Bane, an imposing terrorist, attacks Gotham City and disrupts its eight-year-long period of peace. This forces Bruce Wayne to come out of hiding and don the cape and cowl of Batman again.', 'Christian Bale, Tom Hardy, Anne Hathaway', 'https://m.media-amazon.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_SX300.jpg', 0.00),
(79, 'tt0993846', 'The Wolf of Wall Street', 2013, 'Biography', 'Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.', 'Leonardo DiCaprio, Jonah Hill, Margot Robbie', 'https://m.media-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_SX300.jpg', 0.00),
(80, 'tt0120735', 'Lock, Stock and Two Smoking Barrels', 1998, 'Comedy', 'When four small-time criminals lose a rigged poker game against a London kingpin, he gives them one week to settle their enormous debt.', 'Jason Flemyng, Dexter Fletcher, Nick Moran', 'https://m.media-amazon.com/images/M/MV5BMmY1M2M5ZmMtYzllZC00YzAxLTk4MjktZDJkNjA1MTUwMGQ4XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(81, 'tt0107290', 'Jurassic Park', 1993, 'Action', 'An industrialist invites some experts to visit his theme park of cloned dinosaurs. After a power failure, the creatures run loose, putting everyone\'s lives, including his grandchildren\'s, in danger.', 'Sam Neill, Laura Dern, Jeff Goldblum', 'https://m.media-amazon.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1_SX300.jpg', 0.00),
(82, 'tt0088247', 'The Terminator', 1984, 'Action', 'A cyborg assassin from the future attempts to find and kill a young woman who is destined to give birth to a warrior that will lead a resistance to save humankind from extinction.', 'Arnold Schwarzenegger, Linda Hamilton, Michael Biehn', 'https://m.media-amazon.com/images/M/MV5BZmE0YzIxM2QtMGNlMi00MjRmLWE3MWMtOWQzMGVjMmU0YTFmXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(84, 'tt0180093', 'Requiem for a Dream', 2000, 'Drama', 'The drug-induced utopias of four Coney Island people are shattered when their addictions run deep.', 'Ellen Burstyn, Jared Leto, Jennifer Connelly', 'https://m.media-amazon.com/images/M/MV5BN2ZlMjIzZjctYzA2My00ZWYyLWI4ZjctMGI2NWYyNzFiZjAwXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(86, 'tt0083658', 'Blade Runner', 1982, 'Action', 'A blade runner must pursue and terminate four replicants who stole a ship in space and have returned to Earth to find their creator.', 'Harrison Ford, Rutger Hauer, Sean Young', 'https://m.media-amazon.com/images/M/MV5BOWQ4YTBmNTQtMDYxMC00NGFjLTkwOGQtNzdhNmY1Nzc1MzUxXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(87, 'tt0075314', 'Taxi Driver', 1976, 'Crime', 'A mentally unstable veteran works as a nighttime taxi driver in New York City, where the perceived decadence and sleaze fuels his urge for violent action.', 'Robert De Niro, Jodie Foster, Cybill Shepherd', 'https://m.media-amazon.com/images/M/MV5BZDNhMGYwM2UtMTdlZS00MGQ1LWI2YzAtODY5YWI1MjYyNzRmXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(88, 'tt0113277', 'Heat', 1995, 'Action', 'A group of high-end professional thieves start to feel the heat from the LAPD when they unknowingly leave a verbal clue at their latest heist.', 'Al Pacino, Robert De Niro, Val Kilmer', 'https://m.media-amazon.com/images/M/MV5BMTkxYjU1OTMtYWViZC00ZjAzLWI3MDktZGQ2N2VmMjVjNDRlXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(89, 'tt7286456', 'Joker', 2019, 'Crime', 'Arthur Fleck, a party clown and a failed stand-up comedian, leads an impoverished life with his ailing mother. However, when society shuns him and brands him as a freak, he decides to embrace the life of chaos in Gotham City.', 'Joaquin Phoenix, Robert De Niro, Zazie Beetz', 'https://m.media-amazon.com/images/M/MV5BNzY3OWQ5NDktNWQ2OC00ZjdlLThkMmItMDhhNDk3NTFiZGU4XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(91, 'tt0266697', 'Kill Bill: Vol. 1', 2003, 'Action', 'After waking from a four-year coma, a former assassin wreaks vengeance on the team of assassins who betrayed her.', 'Uma Thurman, David Carradine, Daryl Hannah', 'https://m.media-amazon.com/images/M/MV5BZmMyYzJlZmYtY2I3NC00NjAyLTkyZWItZjdjZDI1YTYyYTEwXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(92, 'tt0071315', 'Chinatown', 1974, 'Drama', 'A private detective hired to expose an adulterer in 1930s Los Angeles finds himself caught up in a web of deceit, corruption, and murder.', 'Jack Nicholson, Faye Dunaway, John Huston', 'https://m.media-amazon.com/images/M/MV5BNmRmZTE0NmUtZjhiZi00MzQ3LTk3ZjctN2Q3ODYzY2U3MDk3XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(93, 'tt0086190', 'Star Wars: Episode VI - Return of the Jedi', 1983, 'Action', 'After rescuing Han Solo from Jabba the Hutt, the Rebel Alliance attempts to destroy the second Death Star while Luke struggles to help Darth Vader back from the dark side.', 'Mark Hamill, Harrison Ford, Carrie Fisher', 'https://m.media-amazon.com/images/M/MV5BNWEwOTI0MmUtMGNmNy00ODViLTlkZDQtZTg1YmQ3MDgyNTUzXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(99, 'tt0361748', 'Inglourious Basterds', 2009, 'Adventure', 'In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner\'s vengeful plans for the same.', 'Brad Pitt, Diane Kruger, Eli Roth', 'https://m.media-amazon.com/images/M/MV5BODZhMWJlNjYtNDExNC00MTIzLTllM2ItOGQ2NGVjNDQ3MzkzXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(100, 'tt0089881', 'Ran', 1985, 'Action', 'In Medieval Japan, an elderly warlord retires, handing over his empire to his three sons. However, he vastly underestimates how the new-found power will corrupt them and cause them to turn on each other...and him.', 'Tatsuya Nakadai, Akira Terao, Jinpachi Nezu', 'https://m.media-amazon.com/images/M/MV5BZDk2NDY5YjktMjEyMC00OTJhLTkzM2EtY2Q4Y2RjYzc2Yjk4XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(101, 'tt0091251', 'Come and See', 1985, 'Drama', 'After finding an old rifle, a young boy joins the Soviet resistance movement against ruthless German forces and experiences the horrors of World War II.', 'Aleksey Kravchenko, Olga Mironova, Liubomiras Laucevicius', 'https://m.media-amazon.com/images/M/MV5BNDlkZmVkZDAtZGFmMS00OWIzLWJkY2YtNWE5NjNhNjhiZGE3XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(102, 'tt0121766', 'Star Wars: Episode III - Revenge of the Sith', 2005, 'Action', 'As the Clone Wars nears its end, Obi-Wan Kenobi pursues a new threat, while Anakin Skywalker is lured by Chancellor Palpatine into a sinister plot for galactic domination.', 'Hayden Christensen, Natalie Portman, Ewan McGregor', 'https://m.media-amazon.com/images/M/MV5BNTc4MTc3NTQ5OF5BMl5BanBnXkFtZTcwOTg0NjI4NA@@._V1_SX300.jpg', 0.00),
(103, 'tt0062622', '2001: A Space Odyssey', 1968, 'Adventure', 'When a mysterious artifact is uncovered on the Moon, a spacecraft manned by two humans and one supercomputer is sent to Jupiter to find its origins.', 'Keir Dullea, Gary Lockwood, William Sylvester', 'https://m.media-amazon.com/images/M/MV5BNjU0NDFkMTQtZWY5OS00MmZhLTg3Y2QtZmJhMzMzMWYyYjc2XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(104, 'tt0209144', 'Memento', 2000, 'Drama', 'A former insurance investigator who now suffers from anterograde amnesia uses notes and tattoos to hunt down his wife\'s murderer.', 'Guy Pearce, Carrie-Anne Moss, Joe Pantoliano', 'https://m.media-amazon.com/images/M/MV5BMGQ3Y2Q4NjktN2E4Ny00Y2Q2LTliZDUtZTNiNjRhY2I0NGIyXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(105, 'tt0405159', 'Million Dollar Baby', 2004, 'Drama', 'Frankie, an ill-tempered old coach, reluctantly agrees to train aspiring boxer Maggie. Impressed with her determination and talent, he helps her become the best and the two soon form a close bond.', 'Hilary Swank, Clint Eastwood, Morgan Freeman', 'https://m.media-amazon.com/images/M/MV5BMTkxNzA1NDQxOV5BMl5BanBnXkFtZTcwNTkyMTIzMw@@._V1_SX300.jpg', 0.00),
(106, 'tt0101414', 'Beauty and the Beast', 1991, 'Animation', 'A prince cursed to spend his days as a hideous monster sets out to regain his humanity by earning a young woman\'s love.', 'Paige O\'Hara, Robby Benson, Jesse Corti', 'https://m.media-amazon.com/images/M/MV5BYTY3NDg2YzktYWFjZC00MTExLTlmZDctMGY3MWYzZTlkYTNiXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(107, 'tt0056058', 'Harakiri', 1962, 'Drama', 'When a ronin requesting seppuku at a feudal lord\'s palace is told of the brutal suicide of another ronin who previously visited, he reveals how their pasts are intertwined - and in doing so challenges the clan\'s integrity.', 'Tatsuya Nakadai, Akira Ishihama, Shima Iwashita', 'https://m.media-amazon.com/images/M/MV5BZThiZjU5ZDQtZDI4Mi00ZGYyLTkzOTktYmIzZTFlZTkxYzg5XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(108, 'tt0093058', 'Full Metal Jacket', 1987, 'Drama', 'A pragmatic U.S. Marine observes the dehumanizing effects the Vietnam War has on his fellow recruits from their brutal boot camp training to the bloody street fighting in Hue.', 'Matthew Modine, R. Lee Ermey, Vincent D\'Onofrio', 'https://m.media-amazon.com/images/M/MV5BYWUzNzZkNzUtNDdiYy00Nzk5LTgxMmItNTk0MjRjNjdjNDA0XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(109, 'tt0114709', 'Toy Story', 1995, 'Animation', 'A cowboy doll is profoundly jealous when a new spaceman action figure supplants him as the top toy in a boy\'s bedroom. When circumstances separate them from their owner, the duo have to put aside their differences to return to him.', 'Tom Hanks, Tim Allen, Don Rickles', 'https://m.media-amazon.com/images/M/MV5BZTA3OWVjOWItNjE1NS00NzZiLWE1MjgtZDZhMWI1ZTlkNzYwXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(111, 'tt0075686', 'Annie Hall', 1977, 'Comedy', 'Alvy Singer, a divorced Jewish comedian, reflects on his relationship with ex-lover Annie Hall, an aspiring nightclub singer, which ended abruptly just like his previous marriages.', 'Woody Allen, Diane Keaton, Tony Roberts', 'https://m.media-amazon.com/images/M/MV5BNjZlOWE5N2UtMTdhZC00NjU5LTg2MjYtOGU4NDhhNWNlMmRlXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(112, 'tt0097576', 'Indiana Jones and the Last Crusade', 1989, 'Action', 'In 1938, after his father goes missing while pursuing the Holy Grail, Indiana Jones finds himself up against the Nazis again to stop them from obtaining its powers.', 'Harrison Ford, Sean Connery, Alison Doody', 'https://m.media-amazon.com/images/M/MV5BNGIxNzQ0YzYtMjNmYi00YjBlLWFjNzEtNGE3ZGFmYTczM2MwXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(113, 'tt0118715', 'The Big Lebowski', 1998, 'Comedy', 'Jeff \"The Dude\" Lebowski, mistaken for a millionaire of the same name, seeks restitution for his ruined rug and enlists his bowling buddies to help get it.', 'Jeff Bridges, John Goodman, Julianne Moore', 'https://m.media-amazon.com/images/M/MV5BY2E3OWQ5OWYtYTRkMC00NjVjLWIzZDQtNmRmM2ZiYTIyYmYxXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(114, 'tt0095016', 'Die Hard', 1988, 'Action', 'A New York City cop, John McClane, tries to save his estranged wife and several others taken hostage by terrorists during a Christmas Eve party at the Nakatomi Plaza Skyscraper in Los Angeles, California.', 'Bruce Willis, Alan Rickman, Bonnie Bedelia', 'https://m.media-amazon.com/images/M/MV5BMGNlYmM1NmQtYWExMS00NmRjLTg5ZmEtMmYyYzJkMzljYWMxXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(115, 'tt0082096', 'Das Boot', 1981, 'Drama', 'A German U-boat stalks the frigid waters of the North Atlantic as its young crew experience the sheer terror and claustrophobic life of a submariner in World War II.', 'Jürgen Prochnow, Herbert Grönemeyer, Klaus Wennemann', 'https://m.media-amazon.com/images/M/MV5BNGU0MWZlMTUtM2Y3Ny00NGNmLWE5NmEtN2YxOWQzMGM3ZWYzXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(117, 'tt0100802', 'Total Recall', 1990, 'Action', 'When a man goes in to have virtual vacation memories of the planet Mars implanted in his mind, an unexpected and harrowing series of events forces him to go to the planet for real - or is he?', 'Arnold Schwarzenegger, Sharon Stone, Michael Ironside', 'https://m.media-amazon.com/images/M/MV5BZjRlMzBkOGMtMTA1Ny00ZWI4LTkzMDItOGVkNWJkN2E4ZTkwXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(119, 'tt0892769', 'How to Train Your Dragon', 2010, 'Animation', 'A hapless young Viking who aspires to hunt dragons becomes the unlikely friend of a young dragon himself, and learns there may be more to the creatures than he assumed.', 'Jay Baruchel, Gerard Butler, Christopher Mintz-Plasse', 'https://m.media-amazon.com/images/M/MV5BMjA5NDQyMjc2NF5BMl5BanBnXkFtZTcwMjg5ODcyMw@@._V1_SX300.jpg', 0.00),
(123, 'tt2278388', 'The Grand Budapest Hotel', 2014, 'Comedy', 'A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy in the hotel\'s glorious years under an exceptional concierge.', 'Ralph Fiennes, F. Murray Abraham, Mathieu Amalric', 'https://m.media-amazon.com/images/M/MV5BMzM5NjUxOTEyMl5BMl5BanBnXkFtZTgwNjEyMDM0MDE@._V1_SX300.jpg', 0.00),
(127, 'tt0113247', 'La haine', 1995, 'Crime', '24 hours in the lives of three young men in the French suburbs the day after a violent riot.', 'Vincent Cassel, Hubert Koundé, Saïd Taghmaoui', 'https://m.media-amazon.com/images/M/MV5BMThlMDA3NDYtZGM2Zi00NmJhLThlYWItZjViZTkzZWU1ZWRiXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(128, 'tt0053125', 'North by Northwest', 1959, 'Adventure', 'A New York City advertising executive goes on the run after being mistaken for a government agent by a group of foreign spies, and falls for a woman whose loyalties he begins to doubt.', 'Cary Grant, Eva Marie Saint, James Mason', 'https://m.media-amazon.com/images/M/MV5BZWIzODI2OGItMzM0Ny00OGRmLTlkNmItMDQxMTFmMTk3YmQwXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(129, 'tt0052357', 'Vertigo', 1958, 'Mystery', 'A former San Francisco police detective juggles wrestling with his personal demons and becoming obsessed with the hauntingly beautiful woman he has been hired to trail, who may be deeply disturbed.', 'James Stewart, Kim Novak, Barbara Bel Geddes', 'https://m.media-amazon.com/images/M/MV5BNzEyZTUxMWItMGVhYy00Y2NlLTljYTMtYzBmMzI1YmUyMDBkXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(130, 'tt0043014', 'Sunset Boulevard', 1950, 'Drama', 'A screenwriter develops a dangerous relationship with a faded film star determined to make a triumphant return.', 'William Holden, Gloria Swanson, Erich von Stroheim', 'https://m.media-amazon.com/images/M/MV5BMTU0NTkyNzYwMF5BMl5BanBnXkFtZTgwMDU0NDk5MTI@._V1_SX300.jpg', 0.00),
(131, 'tt0087843', 'Once Upon a Time in America', 1984, 'Crime', 'A former Prohibition-era Jewish gangster returns to the Lower East Side of Manhattan 35 years later, where he must once again confront the ghosts and regrets of his old life.', 'Robert De Niro, James Woods, Elizabeth McGovern', 'https://m.media-amazon.com/images/M/MV5BMDQ0ZTg2OGUtZjMyOC00M2M5LThkMmItZmM2MmUzMmIxMWJhXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(132, 'tt0033467', 'Citizen Kane', 1941, 'Drama', 'Following the death of publishing tycoon Charles Foster Kane, reporters scramble to uncover the meaning of his final utterance: \'Rosebud.\'', 'Orson Welles, Joseph Cotten, Dorothy Comingore', 'https://m.media-amazon.com/images/M/MV5BYjk1ZDJlMmUtOWQ0Zi00MDM5LTk1OGYtODczNjFmMGYwZGVkXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(133, 'tt0070742', 'The Stranger', 1973, 'Sci-Fi', 'An astronaut finds himself on a planet that\'s (almost) exactly like Earth.', 'Glenn Corbett, Cameron Mitchell, Sharon Acker', 'https://m.media-amazon.com/images/M/MV5BMzAwOTM2OWItN2I1MC00ZGYzLWJkODktY2RkN2VhMmIyODE0XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(134, 'tt0119698', 'Princess Mononoke', 1997, 'Animation', 'While seeking to cure himself of a curse, young warrior Ashitaka stumbles into a conflict between the people of Iron Town and Princess Mononoke, a girl raised by wolves, who will stop at nothing to prevent the destruction of her h...', 'Yôji Matsuda, Yuriko Ishida, Yûko Tanaka', 'https://m.media-amazon.com/images/M/MV5BNjAzODViNGEtMjBkYi00N2U5LWJjNjAtY2U0MGJhZTEwOTU0XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(135, 'tt0084787', 'The Thing', 1982, 'Horror', 'A research team in Antarctica is hunted by a shape-shifting alien that assumes the appearance of its victims.', 'Kurt Russell, Wilford Brimley, Keith David', 'https://m.media-amazon.com/images/M/MV5BYTA3NDU5MWEtNTk4Yy00ZDNkLThmZTQtMjU3ZGVhYzAyMzU4XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(136, 'tt0045152', 'Singin\' in the Rain', 1952, 'Comedy', 'A silent film star falls for a chorus girl just as he and his delusionally jealous screen partner are trying to make the difficult transition to talking pictures in 1920s Hollywood.', 'Gene Kelly, Donald O\'Connor, Debbie Reynolds', 'https://m.media-amazon.com/images/M/MV5BMGQzZDFjZWUtZDU4ZS00ZjM3LTgyYmItYjA3YmIwYzRkZWY3XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(137, 'tt0095327', 'Grave of the Fireflies', 1988, 'Animation', 'A young boy and his little sister struggle to survive in Japan during World War II.', 'Tsutomu Tatsumi, Ayano Shiraishi, Akemi Yamaguchi', 'https://m.media-amazon.com/images/M/MV5BNTY5MmE2OGMtN2IxNC00MDY4LTkwMGEtZDUzOTYyNWE0ZTNjXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(138, 'tt0338013', 'Eternal Sunshine of the Spotless Mind', 2004, 'Drama', 'When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories forever.', 'Jim Carrey, Kate Winslet, Tom Wilkinson', 'https://m.media-amazon.com/images/M/MV5BMTY4NzcwODg3Nl5BMl5BanBnXkFtZTcwNTEwOTMyMw@@._V1_SX300.jpg', 0.00),
(139, 'tt0081398', 'Raging Bull', 1980, 'Biography', 'The life of boxer Jake LaMotta, whose violence and temper that led him to the top in the ring destroyed his life outside of it.', 'Robert De Niro, Cathy Moriarty, Joe Pesci', 'https://m.media-amazon.com/images/M/MV5BMjlkYmYyZWQtNTZkOS00ZjA0LWEwNWUtNzE2ZGNiYjg0MjA2XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(141, 'tt0056172', 'Lawrence of Arabia', 1962, 'Adventure', 'The story of T.E. Lawrence, the English officer who successfully united and led the diverse, often warring, Arab tribes during World War I in order to fight the Turks.', 'Peter O\'Toole, Alec Guinness, Anthony Quinn', 'https://m.media-amazon.com/images/M/MV5BYjY0YTQ1OTAtYjEyNy00NTQ4LThlMTQtM2QwYTVhYWFhNjU5XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(142, 'tt0107048', 'Groundhog Day', 1993, 'Comedy', 'A narcissistic, self-centered weatherman finds himself in a time loop on Groundhog Day.', 'Bill Murray, Andie MacDowell, Chris Elliott', 'https://m.media-amazon.com/images/M/MV5BOWE3MjQ3ZDAtNDQ2MC00YjBjLTk0ZWYtNjQ0YzQ4YWE3YTEyXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(143, 'tt0040522', 'Bicycle Thieves', 1948, 'Drama', 'In post-war Italy, a working-class man\'s bicycle is stolen, endangering his efforts to find work. He and his son set out to find it.', 'Lamberto Maggiorani, Enzo Staiola, Lianella Carell', 'https://m.media-amazon.com/images/M/MV5BMjIzMzAyMzg1Nl5BMl5BanBnXkFtZTgwMzMyNzk0MTE@._V1_SX300.jpg', 0.00),
(144, 'tt0112471', 'Before Sunrise', 1995, 'Comedy', 'A young man and woman meet on a train in Europe, and wind up spending one evening together in Vienna. Unfortunately, both know that this will probably be their only night together.', 'Ethan Hawke, Julie Delpy, Andrea Eckert', 'https://m.media-amazon.com/images/M/MV5BZDZhZmI1ZTUtYWI3NC00NTMwLTk3NWMtNDc0OGNjM2I0ZjlmXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(145, 'tt0056592', 'To Kill a Mockingbird', 1962, 'Crime', 'A widowed lawyer in Depression-era Alabama defends a black man against a false rape charge while teaching his young children about the sad reality of prejudice.', 'Gregory Peck, John Megna, Frank Overton', 'https://m.media-amazon.com/images/M/MV5BZTlkYWU4MGEtZmQyYi00OWEzLTgzY2EtYzVjOTEzYzAyNTk1XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(146, 'tt0105695', 'Unforgiven', 1992, 'Drama', 'Retired Old West gunslinger Will Munny reluctantly takes on one last job to avenge an injustice with the help of his old partner and a young would-be gunman calling himself \"The Schofield Kid\".', 'Clint Eastwood, Gene Hackman, Morgan Freeman', 'https://m.media-amazon.com/images/M/MV5BNmZmMzM3YWMtZjg5Yi00M2MxLTg3ZGItNGU4YjQxNDAxM2Q4XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(147, 'tt0051201', 'Witness for the Prosecution', 1957, 'Crime', 'A veteran British barrister must defend his client in a murder trial that has surprise after surprise.', 'Tyrone Power, Marlene Dietrich, Charles Laughton', 'https://m.media-amazon.com/images/M/MV5BNjRhNTQzMzQtMWViMi00ODQ1LTg0MTEtYWE4ZWZlYjM4YjJhXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(148, 'tt0040897', 'The Treasure of the Sierra Madre', 1948, 'Adventure', 'Two down-on-their-luck Americans searching for work in 1920s Mexico convince an old prospector to help them mine for gold in the Sierra Madre Mountains.', 'Humphrey Bogart, Walter Huston, Tim Holt', 'https://m.media-amazon.com/images/M/MV5BOWM1YjFmODEtMWNhMC00YmI1LWI0Y2EtYzg0YTBhZWI4ODE3XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(149, 'tt0116282', 'Fargo', 1996, 'Crime', 'Minnesota car salesman Jerry Lundegaard\'s inept crime falls apart due to his and his henchmen\'s bungling and the persistent police work of the quite pregnant Marge Gunderson.', 'William H. Macy, Frances McDormand, Steve Buscemi', 'https://m.media-amazon.com/images/M/MV5BNjg4MWE0MjEtODFhNy00MjA5LTg5ODktMzgwNWFmZTAwNjBlXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(150, 'tt0042192', 'All About Eve', 1950, 'Drama', 'A seemingly timid but secretly ruthless ingénue insinuates herself into the lives of an aging Broadway star and her circle of theater friends.', 'Bette Davis, Anne Baxter, George Sanders', 'https://m.media-amazon.com/images/M/MV5BMTY2MTAzODI5NV5BMl5BanBnXkFtZTgwMjM4NzQ0MjE@._V1_SX300.jpg', 0.00),
(151, 'tt0476735', 'My Father and My Son', 2005, 'Drama', 'The family of a left-wing journalist is torn apart after the military coup of Turkey in 1980.', 'Çetin Tekindor, Fikret Kuskan, Hümeyra', 'https://m.media-amazon.com/images/M/MV5BZDE3MTBkNmQtNGFjMC00YTcwLWExY2ItN2MyMGZkNWJlMmFmXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(152, 'tt0086250', 'Scarface', 1983, 'Crime', 'In the 1980s, a determined criminal-minded Cuban immigrant becomes the biggest drug smuggler in Miami, and is eventually undone by his own drug addiction.', 'Al Pacino, Michelle Pfeiffer, Steven Bauer', 'https://m.media-amazon.com/images/M/MV5BNDUzYjY0NmUtMDM4OS00Y2Q5LWJiODYtNTk0ZTk0YjZhMTg1XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(153, 'tt0117951', 'Trainspotting', 1996, 'Crime', 'Renton, deeply immersed in the Edinburgh drug scene, tries to clean up and get out despite the allure of drugs and the influence of friends.', 'Ewan McGregor, Ewen Bremner, Jonny Lee Miller', 'https://m.media-amazon.com/images/M/MV5BYmVkNGJkMzQtYWQwOS00OTZmLThjODQtZjNjNzllYzRiNTE0XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(154, 'tt0107207', 'In the Name of the Father', 1993, 'Biography', 'An Irish man\'s coerced confession to an I.R.A. bombing he did not commit results in the imprisonment of his father as well. Meanwhile, a British lawyer fights to clear their names and free them.', 'Daniel Day-Lewis, Pete Postlethwaite, Anthony Brophy', 'https://m.media-amazon.com/images/M/MV5BMGZiZDVjNzYtZWM4ZC00MzVkLThhNDEtMDJlOTBhYzVjMmNhXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(155, 'tt0032551', 'The Grapes of Wrath', 1940, 'Drama', 'An Oklahoma family, driven off their farm by the poverty and hopelessness of the Dust Bowl, joins the westward migration to California, suffering the misfortunes of the homeless in the Great Depression.', 'Henry Fonda, Jane Darwell, John Carradine', 'https://m.media-amazon.com/images/M/MV5BZDgzZjk3OGYtNWI2Ny00MDg3LTgwYWEtNjI1ODAxNjA3ZmFlXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(156, 'tt0021749', 'City Lights', 1931, 'Comedy', 'With the aid of a wealthy erratic tippler, a dewy-eyed tramp who has fallen in love with a blind flower girl accumulates money to be able to help her medically.', 'Charles Chaplin, Virginia Cherrill, Florence Lee', 'https://m.media-amazon.com/images/M/MV5BM2U4NjgzODUtODkyOC00YTE2LTlhNTItYzFlYmM1NTEzZDA2XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(158, 'tt1832382', 'A Separation', 2011, 'Drama', 'A married couple are faced with a difficult decision - to improve the life of their child by moving to another country or to stay in Iran and look after a deteriorating parent who has Alzheimer\'s disease.', 'Payman Maadi, Leila Hatami, Sareh Bayat', 'https://m.media-amazon.com/images/M/MV5BMDM0ZWRmMzctM2M5ZS00ZjU0LWIxN2MtNWNlNGY1ZDhjMDVhXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(159, 'tt0057115', 'The Great Escape', 1963, 'Adventure', 'Allied officers in a German prisoner of war camp during World War II make a daring plan for a mass escape by hundreds of POWs hoping to draw German personnel and resources away from combat operations.', 'Steve McQueen, James Garner, Richard Attenborough', 'https://m.media-amazon.com/images/M/MV5BMDRhNmJjMzEtMWU5MC00YmEyLTg3ZmYtNzYxZTI1ZGU4ZjI1XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(160, 'tt0072890', 'Dog Day Afternoon', 1975, 'Biography', 'Three amateur robbers plan to hold up a Brooklyn bank. A nice, simple robbery: Walk in, take the money, and run. Unfortunately, the supposedly uncomplicated heist suddenly becomes a bizarre nightmare as everything that could go wr...', 'Al Pacino, John Cazale, Penelope Allen', 'https://m.media-amazon.com/images/M/MV5BY2RjNTg2ODMtZWQ4NC00MDdhLWE4MDgtMWFjMjI4ZTIxMGY4XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(163, 'tt0105643', 'Troll 2', 1990, 'Comedy', 'A vacationing family discovers that the entire town they\'re visiting is inhabited by goblins, disguised as humans, who plan to eat them.', 'Michael Paul Stephenson, George Hardy, Margo Prey', 'https://m.media-amazon.com/images/M/MV5BYzJkY2E0ZjEtYjQ4Yy00MmI3LWFhMGItZjllNmJhM2Y5NTBkXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(164, 'tt0046438', 'Tokyo Story', 1953, 'Drama', 'An old couple visit their children and grandchildren in the city, but receive little attention.', 'Chishû Ryû, Chieko Higashiyama, Sô Yamamura', 'https://m.media-amazon.com/images/M/MV5BODdkNzcxZjItMDU2Yy00Y2JlLWFkYTQtNzIwM2Q4MWU5MTU2XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(165, 'tt0048473', 'Pather Panchali', 1955, 'Drama', 'Impoverished priest Harihar Ray, dreaming of a better life for himself and his family, leaves his rural Bengal village in search of work.', 'Kanu Bannerjee, Karuna Bannerjee, Subir Banerjee', 'https://m.media-amazon.com/images/M/MV5BNmZhNzc0ZDMtZDg2My00MjkxLWJjZTctNTljODc2ZjQzMzJkXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(166, 'tt0044741', 'Ikiru', 1952, 'Drama', 'A bureaucrat tries to find meaning in his life after he discovers he has terminal cancer.', 'Takashi Shimura, Nobuo Kaneko, Shin\'ichi Himori', 'https://m.media-amazon.com/images/M/MV5BYWI2MzBhMzItYzQ3OS00N2Q4LTkyZDUtMjM1YTk0NjhkOWRiXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(168, 'tt0405094', 'The Lives of Others', 2006, 'Drama', 'In 1984 East Berlin, an agent of the secret police conducting surveillance on a writer and his lover finds himself becoming increasingly absorbed by their lives.', 'Ulrich Mühe, Martina Gedeck, Sebastian Koch', 'https://m.media-amazon.com/images/M/MV5BYjM1N2Q0YWEtN2E5MC00NDM3LTk2NTEtMTc1NTk5OTA5ZGIzXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(169, 'tt0317705', 'The Incredibles', 2004, 'Animation', 'While trying to lead a quiet suburban life, a family of undercover superheroes are forced into action to save the world.', 'Craig T. Nelson, Samuel L. Jackson, Holly Hunter', 'https://m.media-amazon.com/images/M/MV5BMTY5OTU0OTc2NV5BMl5BanBnXkFtZTcwMzU4MDcyMQ@@._V1_SX300.jpg', 0.00),
(172, 'tt0036868', 'The Best Years of Our Lives', 1946, 'Drama', 'Three traumatized or physically disabled World War II veterans return home to the American Midwest to discover that they and their families have been irreparably changed making readjustment difficult.', 'Myrna Loy, Dana Andrews, Fredric March', 'https://m.media-amazon.com/images/M/MV5BNTgxMzUyODQtMDJmZC00ZGMyLWI3MzAtZTYwYjBjZjFmMzIxXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(174, 'tt0092067', 'Castle in the Sky', 1986, 'Animation', 'Pazu\'s life changes when he meets Sheeta, a girl whom pirates are chasing for her crystal amulet, which has the potential to locate Laputa, a legendary castle floating in the sky.', 'Mayumi Tanaka, Keiko Yokozawa, Kotoe Hatsui', 'https://m.media-amazon.com/images/M/MV5BZjcyMjg2MzktNjg4YS00MjQzLTg0YWQtMjUyZDk2Y2Y0YzZjXkEyXkFqcGc@._V1_SX300.jpg', 0.00);
INSERT INTO `movies` (`movie_id`, `imdb_id`, `title`, `year`, `genre`, `description`, `actors`, `image_url`, `avg_rating`) VALUES
(175, 'tt0112573', 'Braveheart', 1995, 'Biography', 'Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from the tyranny of King Edward I of England.', 'Mel Gibson, Sophie Marceau, Patrick McGoohan', 'https://m.media-amazon.com/images/M/MV5BNGMxZDBhNGQtYTZlNi00N2UzLWI4NDEtNmUzNWM2NTdmZDA0XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(176, 'tt0103639', 'Aladdin', 1992, 'Animation', 'A kind-hearted street urchin and a power-hungry Grand Vizier vie for a magic lamp that has the power to make their deepest wishes come true.', 'Scott Weinger, Robin Williams, Linda Larkin', 'https://m.media-amazon.com/images/M/MV5BMmQwYWZjZGItYzc0OC00ZDllLTg3NjItOWIyOWYwMDljMjAyXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(177, 'tt0061512', 'Cool Hand Luke', 1967, 'Crime', 'A laid-back Southern man is sentenced to two years in a rural prison, but refuses to conform.', 'Paul Newman, George Kennedy, Strother Martin', 'https://m.media-amazon.com/images/M/MV5BYzI1NzBkNmMtOWRmMS00YmY2LTk5MjQtZjAzMmIwZDQ2M2UwXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(178, 'tt0097165', 'Dead Poets Society', 1989, 'Comedy', 'Maverick teacher John Keating returns in 1959 to the prestigious New England boys\' boarding school where he was once a star student, using poetry to embolden his pupils to new heights of self-expression.', 'Robin Williams, Robert Sean Leonard, Ethan Hawke', 'https://m.media-amazon.com/images/M/MV5BMDYwNGVlY2ItMWYxMS00YjZiLWE5MTAtYWM5NWQ2ZWJjY2Q3XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(179, 'tt0080678', 'The Elephant Man', 1980, 'Biography', 'A Victorian surgeon rescues a heavily-disfigured and mistreated young man working as a sideshow freak, who gradually reveals his capacity for kindness, intelligence and sophistication.', 'Anthony Hopkins, John Hurt, Anne Bancroft', 'https://m.media-amazon.com/images/M/MV5BMGE3MDZhNmMtMmUxZS00MDJmLTgxYmQtOGU4ODU0Y2JmNDI1XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(183, 'tt0208092', 'Snatch', 2000, 'Comedy', 'Unscrupulous boxing promoters, violent bookmakers, a Russian gangster, incompetent amateur robbers and supposedly Jewish jewelers fight to track down a priceless stolen diamond.', 'Jason Statham, Brad Pitt, Stephen Graham', 'https://m.media-amazon.com/images/M/MV5BYzk5NjJkMTQtN2IyNC00YWM5LTlhZmMtNGI3MWNhMTU1YTc4XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(188, 'tt0087332', 'Ghostbusters', 1984, 'Action', 'Armed with proton packs, four paranormal investigators battle mischievous ghouls in New York.', 'Bill Murray, Dan Aykroyd, Sigourney Weaver', 'https://m.media-amazon.com/images/M/MV5BMGI0Yjg2ODAtNDYzNi00Njc2LTlkMmMtMmRmYWI5MDE4ZGRkXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(191, 'tt0095765', 'Cinema Paradiso', 1988, 'Drama', 'Salvatore, a famous film director, returns to his hometown for the funeral of the local theater\'s film projectionist, Alfredo. He reminisces about his life as a young boy falling in love with cinema.', 'Philippe Noiret, Enzo Cannavale, Antonella Attili', 'https://m.media-amazon.com/images/M/MV5BMTljNzc4YWEtYTZlMS00ODMyLWIwMTAtNWQxY2VkMDEwYTk5XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(194, 'tt0325980', 'Pirates of the Caribbean: The Curse of the Black Pearl', 2003, 'Action', 'Blacksmith Will Turner teams up with eccentric pirate \"Captain\" Jack Sparrow to save Elizabeth Swann, the governor\'s daughter and his love, from Jack\'s former pirate allies, who are now undead.', 'Johnny Depp, Geoffrey Rush, Orlando Bloom', 'https://m.media-amazon.com/images/M/MV5BNDhlMzEyNzItMTA5Mi00YWRhLThlNTktYTQyMTA0MDIyNDEyXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(196, 'tt0435761', 'Toy Story 3', 2010, 'Animation', 'The toys are mistakenly delivered to a day-care center instead of the attic right before Andy leaves for college, and it\'s up to Woody to convince the other toys that they weren\'t abandoned and to return home.', 'Tom Hanks, Tim Allen, Joan Cusack', 'https://m.media-amazon.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg', 0.00),
(198, 'tt0266543', 'Finding Nemo', 2003, 'Animation', 'After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.', 'Albert Brooks, Ellen DeGeneres, Alexander Gould', 'https://m.media-amazon.com/images/M/MV5BMTc5NjExNTA5OV5BMl5BanBnXkFtZTYwMTQ0ODY2._V1_SX300.jpg', 0.00),
(201, 'tt1130884', 'Shutter Island', 2010, 'Drama', 'Two US marshals are sent to a mental institution on an inhospitable island in order to investigate the disappearance of a patient.', 'Leonardo DiCaprio, Emily Mortimer, Mark Ruffalo', 'https://m.media-amazon.com/images/M/MV5BN2FjNWExYzEtY2YzOC00YjNlLTllMTQtNmIwM2Q1YzBhOWM1XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(203, 'tt2380307', 'Coco', 2017, 'Animation', 'Aspiring musician Miguel, confronted with his family\'s ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.', 'Anthony Gonzalez, Gael García Bernal, Benjamin Bratt', 'https://m.media-amazon.com/images/M/MV5BMDIyM2E2NTAtMzlhNy00ZGUxLWI1NjgtZDY5MzhiMDc5NGU3XkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(208, 'tt0096874', 'Back to the Future Part II', 1989, 'Adventure', 'After visiting 2015, Marty McFly must repeat his visit to 1955 to prevent disastrous changes to 1985, without interfering with his first trip.', 'Michael J. Fox, Christopher Lloyd, Lea Thompson', 'https://m.media-amazon.com/images/M/MV5BMTNlOTRmOTEtMTAyMi00NjFiLTk3NDMtNWI0YzA3ZTZlYjZiXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(211, 'tt0264464', 'Catch Me If You Can', 2002, 'Biography', 'Barely 17 yet, Frank is a skilled forger who has passed as a doctor, lawyer and pilot. FBI agent Carl becomes obsessed with tracking down the con man, who only revels in the pursuit.', 'Leonardo DiCaprio, Tom Hanks, Christopher Walken', 'https://m.media-amazon.com/images/M/MV5BMTY5MzYzNjc5NV5BMl5BanBnXkFtZTYwNTUyNTc2._V1_SX300.jpg', 0.00),
(213, 'tt0364569', 'Oldboy', 2003, 'Action', 'After being kidnapped and imprisoned for fifteen years, Oh Dae-Su is released, only to find that he must track down his captor in five days.', 'Choi Min-sik, Yoo Ji-tae, Kang Hye-jeong', 'https://m.media-amazon.com/images/M/MV5BMTAwNzNjYWItZmI0Ni00ZTcyLWIwNWMtZjlmNGMxZTEyYTJmXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(214, 'tt0120338', 'Titanic', 1997, 'Drama', 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.', 'Leonardo DiCaprio, Kate Winslet, Billy Zane', 'https://m.media-amazon.com/images/M/MV5BYzYyN2FiZmUtYWYzMy00MzViLWJkZTMtOGY1ZjgzNWMwN2YxXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(217, 'tt0119488', 'L.A. Confidential', 1997, 'Crime', 'As corruption grows in 1950s Los Angeles, three policemen - one strait-laced, one brutal, and one sleazy - investigate a series of murders with their own brand of justice.', 'Kevin Spacey, Russell Crowe, Guy Pearce', 'https://m.media-amazon.com/images/M/MV5BODdiMjY1OGYtNDk0NC00NGQ1LWI4MDItOTJhMTM0YjE1YTAzXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(218, 'tt0108500', 'The Visitors', 1993, 'Comedy', 'A medieval knight and his servant ask a familiar wizard to move them back in time to prevent father-in-law\'s accidentally killing. Instead, they fly away to the 20th century.', 'Christian Clavier, Jean Reno, Valérie Lemercier', 'https://m.media-amazon.com/images/M/MV5BY2RhYjBlMTMtNTQxZS00ZDI3LWJiZTEtZDRkZGY3NmNhM2VlXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(221, 'tt0177789', 'Galaxy Quest', 1999, 'Adventure', 'The alumni cast of a space opera television series have to play their roles as the real thing when an alien race needs their help. However, they also have to defend both Earth and the alien race from a reptilian warlord.', 'Tim Allen, Sigourney Weaver, Alan Rickman', 'https://m.media-amazon.com/images/M/MV5BZmJkYmNhMGMtMDYyNC00ZDEyLWE2ZjAtYTg5OWViODJlNDdmXkEyXkFqcGc@._V1_SX300.jpg', 0.00),
(229, 'tt0078748', 'Alien', 1979, 'Horror', 'After investigating a mysterious transmission of unknown origin, the crew of a commercial spacecraft encounters a deadly lifeform.', 'Sigourney Weaver, Tom Skerritt, John Hurt', 'https://m.media-amazon.com/images/M/MV5BN2NhMDk2MmEtZDQzOC00MmY5LThhYzAtMDdjZGFjOGZjMjdjXkEyXkFqcGc@._V1_SX300.jpg', 0.00);

-- --------------------------------------------------------

--
-- Table structure for table `reviews`
--

DROP TABLE IF EXISTS `reviews`;
CREATE TABLE IF NOT EXISTS `reviews` (
  `review_id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `movie_id` int(11) NOT NULL,
  `rating` int(11) DEFAULT NULL,
  `comment` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`review_id`),
  KEY `user_id` (`user_id`),
  KEY `movie_id` (`movie_id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `reviews`
--

INSERT INTO `reviews` (`review_id`, `user_id`, `movie_id`, `rating`, `comment`, `created_at`) VALUES
(9, 5, 19, 5, 'ghaghera', '2026-03-24 10:34:56'),
(10, 5, 27, 5, 'mhgdjkt', '2026-03-24 10:35:08');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `alias` varchar(100) NOT NULL COMMENT 'User alias',
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `role` enum('default','super_reviewer') CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `alias` (`alias`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`user_id`, `alias`, `email`, `password`, `role`, `created_at`) VALUES
(5, 'Web Dev Guy', '12121@ait.nsw.edu.au', '$2y$10$KKNgDU82ovWhkWliovqvwuKfr/aarVJHvoIcnVTYU67DIE8iviwsK', NULL, '2026-03-24 10:34:43');

-- --------------------------------------------------------

--
-- Table structure for table `user_favorites`
--

DROP TABLE IF EXISTS `user_favorites`;
CREATE TABLE IF NOT EXISTS `user_favorites` (
  `user_id` int(11) NOT NULL,
  `movie_id` int(11) NOT NULL,
  PRIMARY KEY (`user_id`,`movie_id`),
  KEY `fk_uf_movie` (`movie_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `user_favorites`
--

INSERT INTO `user_favorites` (`user_id`, `movie_id`) VALUES
(5, 19),
(5, 27);

--
-- Constraints for dumped tables
--

--
-- Constraints for table `reviews`
--
ALTER TABLE `reviews`
  ADD CONSTRAINT `reviews_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `reviews_ibfk_2` FOREIGN KEY (`movie_id`) REFERENCES `movies` (`movie_id`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table `user_favorites`
--
ALTER TABLE `user_favorites`
  ADD CONSTRAINT `fk_uf_movie` FOREIGN KEY (`movie_id`) REFERENCES `movies` (`movie_id`) ON DELETE CASCADE,
  ADD CONSTRAINT `fk_uf_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
